"use client";
import { ThemeProvider } from "@/components/theme-provider";
// import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { useState } from "react";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "700"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
    const [isUserAuthenticated , setIsUserAuthenticated] = useState(false);


  return (
    <html lang="en">
      <body className={`${nunito.className} min-w-80 antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header isUserAuthenticated={isUserAuthenticated} setIsUserAuthenticated={setIsUserAuthenticated}/>
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
